name: fresh_fruits_final
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  assets:
    - assets/images/
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/main2.png"
  adaptive_icon_background: "#FEC54B"
  adaptive_icon_foreground: "assets/images/main2.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  fullscreen: false
  android_gravity: bottom
  android_12:
    image: assets/images/logo.png
